import React from "react";
import Navbar from "@/components/avidelux/Navbar";
import Footer from "@/components/avidelux/Footer";
import SectionReveal from "@/components/avidelux/SectionReveal";
import PageTransition from "@/components/avidelux/PageTransition";
import SEO from "@/components/avidelux/SEO";

const sections = [
  {
    title: "1. Service provider",
    paragraphs: [
      "Freera UG (haftungsbeschränkt), 45475 Mülheim an der Ruhr, Germany, VAT ID: DE369532975, operating the Avidelux platform and brand. Referred to herein as \"Avidelux\", \"we\", or \"us\".",
    ],
  },
  {
    title: "2. Scope of services",
    paragraphs: ["Avidelux provides a B2B mobility platform offering:"],
    list: [
      "Automated booking ingestion from corporate portals via API, webhook, and email parsing",
      "Automated dispatch to partner taxi and fleet companies using a tiered cascade system",
      "SaaS dashboard for taxi and fleet operators including dispatch management, GPS tracking, driver management, vehicle management, and accounting",
      "Outbound booking confirmation and status updates to client portals",
      "CO₂ emission reporting per trip for CSRD compliance purposes",
    ],
  },
  {
    title: "3. B2B only — no consumer services",
    paragraphs: [
      "Avidelux operates exclusively in a B2B capacity. All services are provided to registered businesses. Avidelux is not a taxi company, does not own vehicles, and does not employ drivers. We act as a technology broker and dispatch platform.",
    ],
  },
  {
    title: "4. Pricing and margin",
    paragraphs: [
      "Avidelux receives bookings from booking portals at a gross price and dispatches them to fleet partners at a net price. The difference constitutes Avidelux's service margin. Fleet partners receive and are invoiced for the net amount only. Gross pricing information is confidential and is not disclosed to fleet partners.",
      "SaaS subscription fees, per-trip fees, and any other charges are set out in the applicable order form or service agreement signed between Avidelux and the client.",
    ],
  },
  {
    title: "5. Client obligations",
    paragraphs: ["Clients using the Avidelux platform agree to:"],
    list: [
      "Provide accurate company information and maintain a valid VAT registration number",
      "Use the platform only for lawful B2B transport booking and management purposes",
      "Not attempt to reverse-engineer, scrape, or circumvent the platform's security measures",
      "Maintain confidentiality of API keys, login credentials, and access tokens",
      "Notify Avidelux immediately of any suspected unauthorised access",
      "Ensure that all bookings submitted comply with applicable local transport regulations",
    ],
  },
  {
    title: "6. Fleet partner obligations",
    paragraphs: ["Fleet partners accepting bookings through the Avidelux platform agree to:"],
    list: [
      "Maintain valid transport licences and insurance for all operating vehicles and drivers",
      "Accept or decline dispatched bookings within the specified timeout period",
      "Fulfil accepted bookings to the standard described in the booking details",
      "Not contact the end passenger or corporate client directly for future bookings outside the platform",
      "Not disclose the platform's commission or margin structure to end clients",
    ],
  },
  {
    title: "7. Availability and uptime",
    paragraphs: [
      "Avidelux targets 99.5% platform availability. Planned maintenance will be communicated with at least 24 hours' notice where possible. We are not liable for downtime caused by third-party providers (booking portals, GPS systems, SMS gateways) outside our control.",
    ],
  },
  {
    title: "8. Data and GoBD compliance",
    paragraphs: [
      "All financial transaction records generated by the platform are maintained as append-only entries in compliance with German GoBD (Grundsätze zur ordnungsmäßigen Führung und Aufbewahrung von Büchern) requirements. Records are retained for a minimum of 10 years. No financial record may be modified or deleted once created.",
    ],
  },
  {
    title: "9. Limitation of liability",
    paragraphs: ["Avidelux's liability is limited to direct damages caused by our proven gross negligence or wilful misconduct. We are not liable for:"],
    list: [
      "Actions or omissions of fleet partners after booking acceptance",
      "Delays, cancellations, or no-shows by fleet partners",
      "Loss of business, indirect, or consequential damages",
      "Force majeure events including natural disasters, strikes, or regulatory changes",
      "Failures of third-party booking portals or API providers",
    ],
    afterList: "Our total liability in any calendar year shall not exceed the total fees paid by the client in that year.",
  },
  {
    title: "10. Intellectual property",
    paragraphs: [
      "All software, algorithms, interfaces, and documentation comprising the Avidelux platform are the exclusive intellectual property of Freera UG. Clients receive a limited, non-exclusive, non-transferable licence to use the platform for their internal business purposes during the term of their service agreement.",
    ],
  },
  {
    title: "11. Confidentiality",
    paragraphs: [
      "Both parties agree to keep confidential all non-public information received from the other party, including pricing, technical specifications, client lists, and business processes. This obligation survives termination of the service agreement for 3 years.",
    ],
  },
  {
    title: "12. Termination",
    paragraphs: [
      "Either party may terminate the service agreement with 30 days' written notice. Avidelux may terminate immediately in cases of material breach, non-payment, or misuse of the platform. Upon termination, client data will be made available for export for 30 days, after which it will be deleted (subject to legal retention obligations).",
    ],
  },
  {
    title: "13. Governing law and jurisdiction",
    paragraphs: [
      "These Terms & Conditions are governed by German law, excluding the UN Convention on Contracts for the International Sale of Goods (CISG). The exclusive place of jurisdiction for all disputes is Duisburg, Germany, provided the client is a registered business (Kaufmann).",
    ],
  },
  {
    title: "14. EU online dispute resolution",
    paragraphs: [
      "eu-odr",
    ],
  },
  {
    title: "15. Changes to these terms",
    paragraphs: [
      "We may update these terms with 30 days' notice to active clients via email. Continued use of the platform after the notice period constitutes acceptance of the updated terms.",
    ],
  },
  {
    title: "16. Contact",
    paragraphs: [
      "contact-email",
    ],
  },
];

export default function Terms() {
  return (
    <PageTransition>
      <SEO
        title="Terms & Conditions"
        description="Terms & Conditions governing the use of the AviDelux B2B mobility platform and services, operated by Freera UG (haftungsbeschränkt)."
        path="/terms"
      />
      <Navbar />

      <section className="pt-32 pb-12">
        <div className="max-w-7xl mx-auto px-6 lg:px-12">
          <SectionReveal>
            <p className="font-body text-xs tracking-[0.3em] uppercase text-bronze mb-6">Legal</p>
          </SectionReveal>
          <SectionReveal delay={0.1}>
            <h1 className="font-heading text-4xl md:text-5xl lg:text-6xl font-bold text-cacao leading-[1.08]">
              Terms &amp; Conditions
            </h1>
          </SectionReveal>
          <SectionReveal delay={0.2}>
            <p className="font-body text-base text-cacao/50 mt-8 leading-relaxed max-w-xl">
              Governing the use of the Avidelux platform and services.
            </p>
          </SectionReveal>
          <SectionReveal delay={0.3}>
            <p className="font-body text-xs text-cacao/40 mt-4">Last updated: June 2026</p>
          </SectionReveal>
        </div>
      </section>

      <section className="pb-24">
        <div className="max-w-3xl mx-auto px-6">
          <SectionReveal>
            <div className="bg-cream border border-bronze/20 rounded-sm p-6 mb-4">
              <p className="font-body text-sm text-cacao/70 leading-relaxed">
                These Terms &amp; Conditions govern the relationship between Freera UG (operating as Avidelux) and business clients using the Avidelux B2B platform. By accessing or using the platform, you agree to these terms.
              </p>
            </div>
          </SectionReveal>

          {sections.map((section, i) => (
            <SectionReveal key={i} delay={i * 0.03}>
              <div className={`py-10 ${i !== sections.length - 1 ? "border-b border-cacao/10" : ""}`}>
                <h2 className="font-heading text-xl md:text-2xl font-semibold text-cacao mb-4">
                  {section.title}
                </h2>
                {section.paragraphs.map((p, j) => {
                  if (p === "eu-odr") {
                    return (
                      <p key={j} className="font-body text-sm text-cacao/60 leading-relaxed mb-3">
                        The European Commission provides a platform for online dispute resolution:{" "}
                        <a
                          href="https://ec.europa.eu/consumers/odr"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-bronze hover:text-cacao luxury-transition"
                        >
                          https://ec.europa.eu/consumers/odr
                        </a>
                        . As we operate exclusively B2B, we are not obligated to participate in consumer arbitration proceedings.
                      </p>
                    );
                  }
                  if (p === "contact-email") {
                    return (
                      <p key={j} className="font-body text-sm text-cacao/60 leading-relaxed mb-3">
                        For any questions regarding these terms:{" "}
                        <a href="mailto:info@avidelux.com" className="text-bronze hover:text-cacao luxury-transition">
                          info@avidelux.com
                        </a>
                      </p>
                    );
                  }
                  return (
                    <p key={j} className="font-body text-sm text-cacao/60 leading-relaxed mb-3">
                      {p}
                    </p>
                  );
                })}
                {section.list && (
                  <ul className="space-y-3 my-2">
                    {section.list.map((item, k) => (
                      <li key={k} className="font-body text-sm text-cacao/60 leading-relaxed flex gap-3">
                        <span className="text-bronze flex-shrink-0">—</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                )}
                {section.afterList && (
                  <p className="font-body text-sm text-cacao/60 leading-relaxed mt-3">{section.afterList}</p>
                )}
              </div>
            </SectionReveal>
          ))}
        </div>
      </section>

      <Footer />
    </PageTransition>
  );
}
